#!/usr/bin/env bash

# neovim
rm -rf ~/.config/nvim
ln -s $(pwd)/nvim ~/.config/nvim

# tmux
rm -rf ~/.tmux.conf
ln -s $(pwd)/tmux/.tmux.conf ~/.tmux.conf

# zsh
rm -rf ~/.zshrc 

if [[ $(grep -i Microsoft /proc/version) ]]; then
    echo "Bash is running on WSL"
    ln -s $(pwd)/zsh/.zshrc-win ~/.zshrc
else
    ln -s $(pwd)/zsh/.zshrc ~/.zshrc
fi

# .local/bin
rm ~/.local/bin/tmux-sessionizer || true
ln -s $(pwd)/localbin/tmux-sessionizer ~/.local/bin/tmux-sessionizer

