#!/usr/bin/env bash

# neovim
rm -rf ~/.config/nvim
ln -s $(pwd)/nvim ~/.config/nvim

# tmux
rm -rf ~/.tmux.conf
ln -s $(pwd)/tmux/.tmux.conf ~/.tmux.conf

# zsh
rm -rf ~/.zshrc 
rm -rf ~/.shell_aliases
rm -rf ~/.shell_exports
rm -rf ~/.shell_utils

ln -s $(pwd)/zsh/.shell_aliases ~/.shell_aliases
ln -s $(pwd)/zsh/.shell_exports ~/.shell_exports
ln -s $(pwd)/zsh/.shell_utils ~/.shell_utils

if [[ $(uname -a) =~ [Dd]arwin ]]; then
    echo "Running on macOS"
    ln -s "$(pwd)/zsh/.zshrc" ~/.zshrc
elif [[ $(grep -i Microsoft /proc/version) ]]; then
    echo "Running on WSL"
    ln -s $(pwd)/zsh/.zshrc-win ~/.zshrc
else
    echo "Running on Linux"
    ln -s $(pwd)/zsh/.zshrc ~/.zshrc
fi

# starship prompt
rm -rf ~/.config/starship.toml
ln -s $(pwd)/starship/starship.toml ~/.config/starship.toml

# .local/bin
rm ~/.local/bin/tmux-sessionizer || true
ln -s $(pwd)/localbin/tmux-sessionizer ~/.local/bin/tmux-sessionizer

